# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  scan-source:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs shiftleft source code scan on demo-app repo
      - name: Run ShiftLeft Source Code Scan
        env: 
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          chmod +x ./shiftleft
          git clone https://github.com/chkp-rolandop/demo-app
          ./shiftleft code-scan -sevt 4 -s ./demo-app

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Container Image
        env: 
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          git clone https://github.com/chkp-rolandop/demo-app
          docker build -t rolandopcp/myapp ./demo-app
          docker save -o myapp.tar rolandopcp/myapp
          chmod +x ./shiftleft
          ./shiftleft image-scan -i myapp.tar

  verify-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Terraform
        env:
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          git clone https://github.com/chkp-rolandop/demo-app
          chmod +x ./shiftleft
          ./shiftleft iac-assessment -r -64 -p ./demo-app/terraform-template
